#!/usr/bin/env python3
"""
stochastic_fem_solver.py

Memory-safe stochastic Q4 FEM solver with optional spatially correlated
Young's modulus fields generated by a low-rank Karhunen-Loeve/Nystrom model.

Supported E_mode values:
- uniform_bounded
- gaussian_clipped
- kl_lognormal

The KL implementation avoids forming the full NxN covariance matrix.
Instead it uses a landmark/Nystrom approximation on element centroids.
This is suitable for large meshes where N can be O(1e5).
"""
from __future__ import annotations

import json
import logging
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, Optional, Tuple

import meshio
import numpy as np
import scipy.sparse as sp
import scipy.sparse.linalg as spla
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.append(str(ROOT))
from src.run_manifest import load_run_manifest, write_run_manifest

from src.configs.geometry import geometry_payload
from src.configs.material import material_payload
from src.configs.run_io import load_runtime_config, update_runtime_config


@dataclass
class SolverConfig:
    base_out_dir: Path = Path("Data/New Data")
    run_name: Optional[str] = None
    run_dir: Optional[Path] = None

    geometry_type: str = "plate_edge_crack"  # plate_edge_crack or plate_hole_edge_crack

    # Geometry
    W: float = 0.2
    H: float = 0.1
    a: float = 0.040
    crack_gap: float = 5e-5
    hole_radius: float = 0.010
    hole_center: Optional[Tuple[float, float]] = None

    # Material
    E_mean: float = 73.1e9
    nu: float = 0.33
    plane_stress: bool = True
    thickness: float = 0.002

    # Stochastic material settings
    stochastic_E: bool = True
    E_mode: str = "uniform_bounded"  # uniform_bounded, gaussian_clipped, kl_lognormal
    E_rel_std: float = 0.005
    E_rel_clip: float = 0.005
    random_seed: int = 5
    n_realizations: int = 5

    # KL / random field settings (used when E_mode == "kl_lognormal")
    kl_n_terms: int = 24
    kl_landmarks: int = 250
    kl_corr_len_x: float = 0.05
    kl_corr_len_y: float = 0.05
    kl_kernel: str = "squared_exponential"  # squared_exponential or exponential
    kl_chunk_size: int = 4000
    kl_jitter: float = 1e-10
    kl_var_tol: float = 0.99

    # Boundary conditions / loading
    fix_bottom_uy: bool = True
    traction_top: Tuple[float, float] = (0.0, +50e6)
    traction_bottom: Tuple[float, float] = (0.0, 0.0)

    # File names
    msh_name: str = "mesh_q4.msh"
    vtk_name: str = "solution_q4.vtk"
    npz_name: str = "fields.npz"
    meta_name: str = "metadata.json"


def setup_logging():
    logging.basicConfig(level=logging.INFO, format="[%(levelname)s] %(message)s")


def crack_tip_xy(cfg: SolverConfig) -> Tuple[float, float]:
    if cfg.geometry_type == "plate_edge_crack":
        return (cfg.a, 0.0)
    if cfg.geometry_type == "plate_hole_edge_crack":
        cx, cy = cfg.hole_center if cfg.hole_center is not None else (cfg.W / 2.0, 0.0)
        return (cx + cfg.hole_radius + cfg.a, cy)
    raise ValueError(f"Unsupported geometry_type={cfg.geometry_type!r}")


def crack_start_xy(cfg: SolverConfig) -> Tuple[float, float]:
    if cfg.geometry_type == "plate_edge_crack":
        return (0.0, 0.0)
    if cfg.geometry_type == "plate_hole_edge_crack":
        cx, cy = cfg.hole_center if cfg.hole_center is not None else (cfg.W / 2.0, 0.0)
        return (cx + cfg.hole_radius, cy)
    raise ValueError(f"Unsupported geometry_type={cfg.geometry_type!r}")


def read_gmsh_quad_mesh(msh_path: Path):
    m = meshio.read(str(msh_path))
    pts = np.asarray(m.points[:, :2], dtype=float)

    quad_blocks = []
    line_blocks = []
    line_phys_blocks = []

    phys_blocks = None
    if m.cell_data and "gmsh:physical" in m.cell_data:
        phys_blocks = m.cell_data["gmsh:physical"]

    for i, block in enumerate(m.cells):
        if block.type in ("quad", "quad4", "quadrilateral"):
            quad_blocks.append(np.asarray(block.data, dtype=int))
        elif block.type == "line":
            line_blocks.append(np.asarray(block.data, dtype=int))
            if phys_blocks is not None and i < len(phys_blocks):
                arr = np.asarray(phys_blocks[i], dtype=int)
                if len(arr) == len(block.data):
                    line_phys_blocks.append(arr)

    if not quad_blocks:
        raise ValueError("No quad cells found.")

    quad = np.vstack(quad_blocks)
    lines = np.vstack(line_blocks) if line_blocks else None
    line_phys = np.concatenate(line_phys_blocks) if line_phys_blocks else None

    phys_map: Dict[int, str] = {}
    if hasattr(m, "field_data") and m.field_data:
        for name, (pid, dim) in m.field_data.items():
            phys_map[int(pid)] = name

    logging.info(f"Read mesh: {msh_path}")
    logging.info(f"Cell blocks: {[blk.type for blk in m.cells]}")
    logging.info(f"Physical groups found: {phys_map}")
    logging.info(
        f"lines={'yes' if lines is not None else 'no'}, "
        f"line_phys={'yes' if line_phys is not None else 'no'}"
    )

    return pts, quad, lines, line_phys, phys_map


def boundary_edges_from_geometry(
    pts: np.ndarray,
    quad: np.ndarray,
    name: str,
    W: float,
    H: float,
) -> np.ndarray:
    tol = 1e-8 * max(W, H)
    edge_count = {}

    for elem in quad:
        local_edges = [
            (elem[0], elem[1]),
            (elem[1], elem[2]),
            (elem[2], elem[3]),
            (elem[3], elem[0]),
        ]
        for i, j in local_edges:
            e = tuple(sorted((int(i), int(j))))
            edge_count[e] = edge_count.get(e, 0) + 1

    boundary_edges = [e for e, c in edge_count.items() if c == 1]

    selected = []
    for i, j in boundary_edges:
        x1, y1 = pts[i]
        x2, y2 = pts[j]

        if name == "TOP":
            if abs(y1 - H / 2.0) < tol and abs(y2 - H / 2.0) < tol:
                selected.append([i, j])
        elif name == "BOTTOM":
            if abs(y1 + H / 2.0) < tol and abs(y2 + H / 2.0) < tol:
                selected.append([i, j])
        elif name == "LEFT":
            if abs(x1 - 0.0) < tol and abs(x2 - 0.0) < tol:
                selected.append([i, j])
        elif name == "RIGHT":
            if abs(x1 - W) < tol and abs(x2 - W) < tol:
                selected.append([i, j])
        else:
            raise ValueError(f"Unsupported boundary name {name!r}")

    arr = np.asarray(selected, dtype=int)
    if arr.size == 0:
        raise ValueError(f"Could not infer boundary '{name}' from quad geometry.")
    return arr


def boundary_edges_by_name(
    pts: np.ndarray,
    quad: np.ndarray,
    lines,
    line_phys,
    phys_map,
    name: str,
    W: float,
    H: float,
) -> np.ndarray:
    if lines is not None and line_phys is not None:
        pid = next((k for k, v in phys_map.items() if v == name), None)
        if pid is not None:
            edges = lines[line_phys == pid]
            if len(edges) > 0:
                logging.info(f"Using physical-group boundary '{name}' with {len(edges)} edges.")
                return edges

    logging.warning(
        f"Physical-tag lookup failed for boundary '{name}'. "
        f"Falling back to geometric boundary detection."
    )
    edges = boundary_edges_from_geometry(pts, quad, name, W, H)
    logging.info(f"Using geometric boundary '{name}' with {len(edges)} edges.")
    return edges


def D_matrix(E: float, nu: float, plane_stress: bool) -> np.ndarray:
    if plane_stress:
        c = E / (1.0 - nu**2)
        return c * np.array(
            [[1.0, nu, 0.0], [nu, 1.0, 0.0], [0.0, 0.0, (1.0 - nu) / 2.0]], dtype=float
        )
    c = E / ((1.0 + nu) * (1.0 - 2.0 * nu))
    return c * np.array(
        [[1.0 - nu, nu, 0.0], [nu, 1.0 - nu, 0.0], [0.0, 0.0, (1.0 - 2.0 * nu) / 2.0]], dtype=float
    )


def q4_shape(xi: float, eta: float):
    N = np.array(
        [
            0.25 * (1 - xi) * (1 - eta),
            0.25 * (1 + xi) * (1 - eta),
            0.25 * (1 + xi) * (1 + eta),
            0.25 * (1 - xi) * (1 + eta),
        ],
        dtype=float,
    )
    dN_dxi = np.array(
        [
            [-0.25 * (1 - eta), -0.25 * (1 - xi)],
            [0.25 * (1 - eta), -0.25 * (1 + xi)],
            [0.25 * (1 + eta), 0.25 * (1 + xi)],
            [-0.25 * (1 + eta), 0.25 * (1 - xi)],
        ],
        dtype=float,
    )
    return N, dN_dxi


def q4_B_matrix(xe: np.ndarray, xi: float, eta: float):
    _, dN_dxi = q4_shape(xi, eta)
    J = xe.T @ dN_dxi
    detJ = float(np.linalg.det(J))
    if detJ <= 0:
        raise ValueError(f"Non-positive detJ={detJ}")
    invJ = np.linalg.inv(J)
    dN_dx = dN_dxi @ invJ.T

    B = np.zeros((3, 8), dtype=float)
    for a in range(4):
        dNdx, dNdy = dN_dx[a, 0], dN_dx[a, 1]
        B[0, 2 * a] = dNdx
        B[1, 2 * a + 1] = dNdy
        B[2, 2 * a] = dNdy
        B[2, 2 * a + 1] = dNdx
    return B, detJ


def element_centroids(pts: np.ndarray, quad: np.ndarray) -> np.ndarray:
    return np.mean(pts[quad], axis=1)


def _kernel_covariance(Xa: np.ndarray, Xb: np.ndarray, cfg: SolverConfig) -> np.ndarray:
    lx = max(float(cfg.kl_corr_len_x), 1e-14)
    ly = max(float(cfg.kl_corr_len_y), 1e-14)
    dx = (Xa[:, None, 0] - Xb[None, :, 0]) / lx
    dy = (Xa[:, None, 1] - Xb[None, :, 1]) / ly

    if cfg.kl_kernel == "squared_exponential":
        r2 = dx * dx + dy * dy
        return np.exp(-0.5 * r2)
    if cfg.kl_kernel == "exponential":
        r = np.sqrt(dx * dx + dy * dy)
        return np.exp(-r)
    raise ValueError(f"Unsupported kl_kernel={cfg.kl_kernel!r}")


def build_kl_basis(cfg: SolverConfig, centroids: np.ndarray, rng: np.random.Generator) -> dict:
    n = centroids.shape[0]
    if n == 0:
        raise ValueError("No element centroids available for KL basis.")

    m = min(int(cfg.kl_landmarks), n)
    if m < 2:
        raise ValueError("kl_landmarks must be at least 2.")

    landmark_idx = np.sort(rng.choice(n, size=m, replace=False))
    Xl = centroids[landmark_idx]

    logging.info(
        "Building memory-safe KL basis using Nystrom: "
        f"n_elements={n}, landmarks={m}, requested_terms={cfg.kl_n_terms}"
    )

    Kmm = _kernel_covariance(Xl, Xl, cfg)
    Kmm[np.diag_indices_from(Kmm)] += float(cfg.kl_jitter)

    evals_m, evecs_m = np.linalg.eigh(Kmm)
    order = np.argsort(evals_m)[::-1]
    evals_m = np.clip(evals_m[order], 0.0, None)
    evecs_m = evecs_m[:, order]

    pos = evals_m > 1e-14 * max(1.0, evals_m[0] if evals_m.size else 1.0)
    evals_m = evals_m[pos]
    evecs_m = evecs_m[:, pos]
    if evals_m.size == 0:
        raise RuntimeError("All KL landmark eigenvalues were numerically zero.")

    cum = np.cumsum(evals_m) / np.sum(evals_m)
    r_var = int(np.searchsorted(cum, float(cfg.kl_var_tol)) + 1)
    r = min(int(cfg.kl_n_terms), r_var, evals_m.size)
    evals_r = evals_m[:r]
    evecs_r = evecs_m[:, :r]

    Phi = np.empty((n, r), dtype=float)
    chunk = max(int(cfg.kl_chunk_size), 1)
    scale = np.sqrt(m / np.maximum(evals_r, 1e-30))

    for i0 in range(0, n, chunk):
        i1 = min(i0 + chunk, n)
        Kxm = _kernel_covariance(centroids[i0:i1], Xl, cfg)
        Phi[i0:i1, :] = (Kxm @ evecs_r) * scale[None, :]

    # Normalize approximate modes with respect to discrete element inner product.
    norms = np.linalg.norm(Phi, axis=0)
    bad = norms < 1e-14
    norms[bad] = 1.0
    Phi /= norms[None, :]

    # Convert to approximate field eigenvalues in full space.
    lam = np.maximum((n / m) * evals_r * (norms**2), 0.0)

    logging.info(
        "KL basis ready: kept_terms=%d, captured_landmark_variance=%.4f",
        r,
        float(cum[r - 1]),
    )

    return {
        "landmark_idx": landmark_idx,
        "Phi": Phi,
        "lam": lam,
        "captured_var": float(cum[r - 1]),
        "n_elements": int(n),
        "n_landmarks": int(m),
        "n_terms": int(r),
        "kernel": cfg.kl_kernel,
        "corr_len_x": float(cfg.kl_corr_len_x),
        "corr_len_y": float(cfg.kl_corr_len_y),
    }


def sample_elementwise_E(
    cfg: SolverConfig,
    ne: int,
    rng: np.random.Generator,
    kl_data: Optional[dict] = None,
) -> np.ndarray:
    if not cfg.stochastic_E:
        return np.full(ne, cfg.E_mean, dtype=float)

    if cfg.E_mode == "uniform_bounded":
        rel = rng.uniform(-cfg.E_rel_std, cfg.E_rel_std, size=ne)
        return cfg.E_mean * (1.0 + rel)

    if cfg.E_mode == "gaussian_clipped":
        rel = rng.normal(0.0, cfg.E_rel_std, size=ne)
        rel = np.clip(rel, -cfg.E_rel_clip, cfg.E_rel_clip)
        return cfg.E_mean * (1.0 + rel)

    if cfg.E_mode == "kl_lognormal":
        if kl_data is None:
            raise ValueError("kl_data is required when E_mode='kl_lognormal'.")
        Phi = kl_data["Phi"]
        lam = kl_data["lam"]
        r = lam.size
        xi = rng.standard_normal(r)
        g = Phi @ (np.sqrt(lam) * xi)

        # Scale the latent Gaussian field to the requested relative standard deviation.
        std_g = float(np.std(g))
        if std_g < 1e-14:
            rel_field = np.zeros_like(g)
        else:
            rel_field = (cfg.E_rel_std / std_g) * g

        # Lognormal map preserving target mean approximately at E_mean.
        sigma_ln2 = np.log(1.0 + cfg.E_rel_std**2)
        sigma_ln = np.sqrt(max(sigma_ln2, 0.0))
        z = rel_field / max(cfg.E_rel_std, 1e-14)
        E = cfg.E_mean * np.exp(sigma_ln * z - 0.5 * sigma_ln2)
        return E.astype(float, copy=False)

    raise ValueError(f"Unsupported E_mode={cfg.E_mode!r}")


def assemble_global_K(cfg: SolverConfig, pts: np.ndarray, quad: np.ndarray, E_elem: np.ndarray) -> sp.csr_matrix:
    n = pts.shape[0]
    ndof = 2 * n
    g = 1.0 / np.sqrt(3.0)
    gps = [(-g, -g), (g, -g), (g, g), (-g, g)]
    rows, cols, vals = [], [], []
    t = cfg.thickness

    for e in range(quad.shape[0]):
        nodes = quad[e]
        xe = pts[nodes, :]
        D = D_matrix(float(E_elem[e]), cfg.nu, cfg.plane_stress)

        Ke = np.zeros((8, 8), dtype=float)
        for (xi, eta) in gps:
            B, detJ = q4_B_matrix(xe, xi, eta)
            Ke += (B.T @ D @ B) * (detJ * t)

        dofs = np.array(
            [
                2 * nodes[0], 2 * nodes[0] + 1,
                2 * nodes[1], 2 * nodes[1] + 1,
                2 * nodes[2], 2 * nodes[2] + 1,
                2 * nodes[3], 2 * nodes[3] + 1,
            ],
            dtype=int,
        )
        for i_local in range(8):
            for j_local in range(8):
                rows.append(dofs[i_local])
                cols.append(dofs[j_local])
                vals.append(Ke[i_local, j_local])

    return sp.coo_matrix((vals, (rows, cols)), shape=(ndof, ndof)).tocsr()


def assemble_uniform_traction_rhs(cfg: SolverConfig, pts: np.ndarray, boundary_edges: np.ndarray, tx: float, ty: float) -> np.ndarray:
    n = pts.shape[0]
    f = np.zeros(2 * n, dtype=float)
    tvec = np.array([tx, ty], dtype=float)
    for (n1, n2) in boundary_edges:
        L = float(np.linalg.norm(pts[n2] - pts[n1]))
        fe = cfg.thickness * L * 0.5 * tvec
        f[2 * n1 : 2 * n1 + 2] += fe
        f[2 * n2 : 2 * n2 + 2] += fe
    return f


def solve_dirichlet_elimination(K: sp.csr_matrix, f: np.ndarray, fixed_dofs: np.ndarray, fixed_vals: np.ndarray) -> np.ndarray:
    ndof = K.shape[0]
    all_dofs = np.arange(ndof, dtype=int)
    free = np.setdiff1d(all_dofs, fixed_dofs)
    f_mod = f.copy()
    f_mod[free] -= K[free][:, fixed_dofs] @ fixed_vals
    uf = spla.spsolve(K[free][:, free].tocsr(), f_mod[free])

    u = np.zeros(ndof, dtype=float)
    u[free] = uf
    u[fixed_dofs] = fixed_vals
    return u


def compute_cell_stress_vonmises(cfg: SolverConfig, pts: np.ndarray, quad: np.ndarray, u: np.ndarray, E_elem: np.ndarray):
    g = 1.0 / np.sqrt(3.0)
    gps = [(-g, -g), (g, -g), (g, g), (-g, g)]

    sig_cell = np.zeros((quad.shape[0], 3), dtype=float)
    vm_cell = np.zeros(quad.shape[0], dtype=float)

    for e in range(quad.shape[0]):
        nodes = quad[e]
        xe = pts[nodes, :]
        ue = np.column_stack([u[2 * nodes], u[2 * nodes + 1]])
        D = D_matrix(float(E_elem[e]), cfg.nu, cfg.plane_stress)

        sig_acc = np.zeros(3, dtype=float)
        vm_acc = 0.0
        wt_acc = 0.0

        for (xi, eta) in gps:
            _, dN_dxi = q4_shape(xi, eta)
            J = xe.T @ dN_dxi
            detJ = float(np.linalg.det(J))
            invJ = np.linalg.inv(J)
            dN_dx = dN_dxi @ invJ.T
            grad_u = ue.T @ dN_dx
            exx = grad_u[0, 0]
            eyy = grad_u[1, 1]
            gxy = grad_u[0, 1] + grad_u[1, 0]
            eps = np.array([exx, eyy, gxy], dtype=float)
            sig = D @ eps
            sxx, syy, txy = float(sig[0]), float(sig[1]), float(sig[2])
            vm = float(np.sqrt(sxx * sxx - sxx * syy + syy * syy + 3.0 * txy * txy))
            wt = detJ
            sig_acc += sig * wt
            vm_acc += vm * wt
            wt_acc += wt

        sig_cell[e, :] = sig_acc / wt_acc
        vm_cell[e] = vm_acc / wt_acc

    return sig_cell, vm_cell


def write_vtk(out_path: Path, pts: np.ndarray, quad: np.ndarray, u: np.ndarray, sig_cell: np.ndarray, vm_cell: np.ndarray, E_elem: np.ndarray):
    pts3 = np.column_stack([pts[:, 0], pts[:, 1], np.zeros(pts.shape[0])])
    U3 = np.column_stack([u[0::2], u[1::2], np.zeros(pts.shape[0])])
    mesh = meshio.Mesh(
        points=pts3,
        cells=[("quad", quad)],
        point_data={"U": U3},
        cell_data={
            "sigma": [sig_cell],
            "von_mises": [vm_cell],
            "E_realization": [E_elem],
            "sigma_xx": [sig_cell[:, 0]],
            "sigma_yy": [sig_cell[:, 1]],
            "tau_xy": [sig_cell[:, 2]],
        },
    )
    mesh.write(str(out_path))


def solve_one(cfg: SolverConfig, realization_id: int = 0, kl_data: Optional[dict] = None, manifest_hash: Optional[str] = None):
    pts, quad, lines, line_phys, phys_map = read_gmsh_quad_mesh(cfg.run_dir / cfg.msh_name)
    top_edges = boundary_edges_by_name(pts, quad, lines, line_phys, phys_map, "TOP", cfg.W, cfg.H)
    bottom_edges = boundary_edges_by_name(pts, quad, lines, line_phys, phys_map, "BOTTOM", cfg.W, cfg.H)
    centroids = element_centroids(pts, quad)

    rng = np.random.default_rng(cfg.random_seed + realization_id)
    E_elem = sample_elementwise_E(cfg, quad.shape[0], rng, kl_data=kl_data)

    K = assemble_global_K(cfg, pts, quad, E_elem)
    f = assemble_uniform_traction_rhs(cfg, pts, top_edges, cfg.traction_top[0], cfg.traction_top[1])
    f += assemble_uniform_traction_rhs(cfg, pts, bottom_edges, cfg.traction_bottom[0], cfg.traction_bottom[1])

    bottom_nodes = np.unique(bottom_edges.reshape(-1))
    fixed_dofs = list((2 * bottom_nodes + 1).astype(int))
    fixed_vals = list(np.zeros_like(bottom_nodes, dtype=float))

    x_bottom = pts[bottom_nodes, 0]
    x_center = 0.5 * (np.min(x_bottom) + np.max(x_bottom))
    anchor = int(bottom_nodes[np.argmin(np.abs(x_bottom - x_center))])
    fixed_dofs.append(2 * anchor)
    fixed_vals.append(0.0)
    fixed_dofs = np.array(fixed_dofs, dtype=int)
    fixed_vals = np.array(fixed_vals, dtype=float)

    u = solve_dirichlet_elimination(K, f, fixed_dofs, fixed_vals)
    sig_cell, vm_cell = compute_cell_stress_vonmises(cfg, pts, quad, u, E_elem)

    suffix = f"_mc{realization_id:04d}" if cfg.n_realizations > 1 else ""
    write_vtk(cfg.run_dir / f"solution_q4{suffix}.vtk", pts, quad, u, sig_cell, vm_cell, E_elem)
    np.savez(
        cfg.run_dir / f"fields{suffix}.npz",
        pts=pts,
        conn=quad,
        u=u,
        E_elem=E_elem,
        centroids=centroids,
    )

    meta = asdict(cfg)
    for k, v in list(meta.items()):
        if isinstance(v, Path):
            meta[k] = str(v)

    meta["tip"] = list(crack_tip_xy(cfg))
    meta["crack_start"] = list(crack_start_xy(cfg))
    meta["crack_dir"] = [1.0, 0.0]
    meta["realization_id"] = int(realization_id)
    meta["realization_seed"] = int(cfg.random_seed + realization_id)
    meta["seed_derivation_rule"] = "realization_seed = random_seed + realization_id"
    meta["manifest_hash_sha256"] = manifest_hash
    meta["E_elem_mean"] = float(np.mean(E_elem))
    meta["E_elem_std"] = float(np.std(E_elem))
    if kl_data is not None:
        meta["kl"] = {
            "n_elements": int(kl_data["n_elements"]),
            "n_landmarks": int(kl_data["n_landmarks"]),
            "n_terms": int(kl_data["n_terms"]),
            "captured_var": float(kl_data["captured_var"]),
            "kernel": kl_data["kernel"],
            "corr_len_x": float(kl_data["corr_len_x"]),
            "corr_len_y": float(kl_data["corr_len_y"]),
        }

    (cfg.run_dir / f"metadata{suffix}.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")
    logging.info(
        "Finished realization %d: mean(E)=%.6e, std(E)=%.6e",
        realization_id,
        float(np.mean(E_elem)),
        float(np.std(E_elem)),
    )


def solve_from_material_field(
    mesh_path: Path,
    material_field: Optional[np.ndarray] = None,
    E_scalar: Optional[float] = None,
    nu_scalar: Optional[float] = None,
    config: Optional[SolverConfig] = None,
) -> dict:
    """
    Solve a single deterministic FE case from either:
      - prescribed elementwise material field, or
      - scalar E/nu overrides.
    """
    cfg = SolverConfig() if config is None else config
    cfg = SolverConfig(**asdict(cfg))
    mesh_path = Path(mesh_path)
    cfg.run_dir = mesh_path.parent
    cfg.msh_name = mesh_path.name
    if E_scalar is not None:
        cfg.E_mean = float(E_scalar)
    if nu_scalar is not None:
        cfg.nu = float(nu_scalar)
    cfg.stochastic_E = material_field is not None

    pts, quad, lines, line_phys, phys_map = read_gmsh_quad_mesh(mesh_path)
    top_edges = boundary_edges_by_name(pts, quad, lines, line_phys, phys_map, "TOP", cfg.W, cfg.H)
    bottom_edges = boundary_edges_by_name(pts, quad, lines, line_phys, phys_map, "BOTTOM", cfg.W, cfg.H)
    centroids = element_centroids(pts, quad)

    if material_field is None:
        E_elem = np.full(quad.shape[0], float(cfg.E_mean), dtype=float)
    else:
        E_elem = np.asarray(material_field, dtype=float).reshape(-1)
        if E_elem.size != quad.shape[0]:
            raise ValueError("material_field length must match number of mesh elements")

    K = assemble_global_K(cfg, pts, quad, E_elem)
    f = assemble_uniform_traction_rhs(cfg, pts, top_edges, cfg.traction_top[0], cfg.traction_top[1])
    f += assemble_uniform_traction_rhs(cfg, pts, bottom_edges, cfg.traction_bottom[0], cfg.traction_bottom[1])

    bottom_nodes = np.unique(bottom_edges.reshape(-1))
    fixed_dofs = list((2 * bottom_nodes + 1).astype(int))
    fixed_vals = list(np.zeros_like(bottom_nodes, dtype=float))
    x_bottom = pts[bottom_nodes, 0]
    x_center = 0.5 * (np.min(x_bottom) + np.max(x_bottom))
    anchor = int(bottom_nodes[np.argmin(np.abs(x_bottom - x_center))])
    fixed_dofs.append(2 * anchor)
    fixed_vals.append(0.0)

    u = solve_dirichlet_elimination(K, f, np.asarray(fixed_dofs, dtype=int), np.asarray(fixed_vals, dtype=float))
    sig_cell, vm_cell = compute_cell_stress_vonmises(cfg, pts, quad, u, E_elem)
    return {
        "pts": pts,
        "conn": quad,
        "u": u,
        "E_elem": E_elem,
        "centroids": centroids,
        "sigma_cell": sig_cell,
        "von_mises_cell": vm_cell,
    }


def run_single_realization_with_overrides(
    run_dir: Path,
    realization_id: int,
    material_overrides: Optional[dict] = None,
    stochastic_field_overrides: Optional[dict] = None,
    write_outputs: bool = True,
) -> dict:
    """
    Public programmatic API for one stochastic/deterministic realization.
    """
    run_dir = Path(run_dir)
    cfg = SolverConfig(run_dir=run_dir, run_name=run_dir.name)
    runtime_cfg = load_runtime_config(run_dir / "runtime_config.json")
    geom_cfg = runtime_cfg.get("geometry", {})
    mat_cfg = runtime_cfg.get("material", {})
    if geom_cfg:
        cfg.geometry_type = geom_cfg.get("geometry_type", cfg.geometry_type)
        cfg.W = float(geom_cfg.get("W", cfg.W))
        cfg.H = float(geom_cfg.get("H", cfg.H))
        cfg.a = float(geom_cfg.get("a", cfg.a))
    if mat_cfg:
        cfg.E_mean = float(mat_cfg.get("E_mean", mat_cfg.get("E", cfg.E_mean)))
        cfg.nu = float(mat_cfg.get("nu", cfg.nu))
        cfg.plane_stress = bool(mat_cfg.get("plane_stress", cfg.plane_stress))
    if material_overrides:
        if "E" in material_overrides:
            cfg.E_mean = float(material_overrides["E"])
        if "E_mean" in material_overrides:
            cfg.E_mean = float(material_overrides["E_mean"])
        if "nu" in material_overrides:
            cfg.nu = float(material_overrides["nu"])
    if stochastic_field_overrides:
        cfg.E_mode = stochastic_field_overrides.get("E_mode", cfg.E_mode)
        if "E_rel_std" in stochastic_field_overrides:
            cfg.E_rel_std = float(stochastic_field_overrides["E_rel_std"])

    fields = solve_from_material_field(
        mesh_path=run_dir / cfg.msh_name,
        material_field=stochastic_field_overrides.get("material_field") if stochastic_field_overrides else None,
        E_scalar=cfg.E_mean,
        nu_scalar=cfg.nu,
        config=cfg,
    )

    suffix = f"_mc{realization_id:04d}"
    if write_outputs:
        write_vtk(run_dir / f"solution_q4{suffix}.vtk", fields["pts"], fields["conn"], fields["u"], fields["sigma_cell"], fields["von_mises_cell"], fields["E_elem"])
        np.savez(
            run_dir / f"fields{suffix}.npz",
            pts=fields["pts"],
            conn=fields["conn"],
            u=fields["u"],
            E_elem=fields["E_elem"],
            centroids=fields["centroids"],
        )
        meta = asdict(cfg)
        for k, v in list(meta.items()):
            if isinstance(v, Path):
                meta[k] = str(v)
        meta["tip"] = list(crack_tip_xy(cfg))
        meta["crack_start"] = list(crack_start_xy(cfg))
        meta["crack_dir"] = [1.0, 0.0]
        meta["realization_id"] = int(realization_id)
        meta["E_elem_mean"] = float(np.mean(fields["E_elem"]))
        meta["E_elem_std"] = float(np.std(fields["E_elem"]))
        (run_dir / f"metadata{suffix}.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")

    return {
        "run_dir": str(run_dir),
        "realization_id": int(realization_id),
        "fields_path": str(run_dir / f"fields{suffix}.npz"),
        "metadata_path": str(run_dir / f"metadata{suffix}.json"),
        "E_mean": float(np.mean(fields["E_elem"])),
        "E_std": float(np.std(fields["E_elem"])),
    }


def main():
    setup_logging()
    cfg = SolverConfig()
    if cfg.run_name is None:
        cfg.run_name = f"40_mm_{cfg.geometry_type}"
    cfg.run_dir = cfg.base_out_dir / cfg.run_name
    cfg.run_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = cfg.run_dir / "run_manifest.json"
    if manifest_path.exists():
        manifest = load_run_manifest(cfg.run_dir)
        manifest_hash = manifest.get("manifest_hash_sha256")
    else:
        _, manifest_hash = write_run_manifest(
            cfg.run_dir,
            {
                "workflow": "Stochastic_FEM.stochastic_fem_solver",
                "geometry_mesh": {
                    "geometry_type": cfg.geometry_type,
                    "W": cfg.W,
                    "H": cfg.H,
                    "a": cfg.a,
                    "crack_gap": cfg.crack_gap,
                    "hole_radius": cfg.hole_radius,
                    "hole_center": list(cfg.hole_center) if cfg.hole_center is not None else None,
                    "mesh_file": cfg.msh_name,
                },
                "solver": {
                    "E_mean": cfg.E_mean,
                    "nu": cfg.nu,
                    "plane_stress": cfg.plane_stress,
                    "thickness": cfg.thickness,
                    "stochastic_E": cfg.stochastic_E,
                    "E_mode": cfg.E_mode,
                    "E_rel_std": cfg.E_rel_std,
                    "E_rel_clip": cfg.E_rel_clip,
                    "n_realizations": cfg.n_realizations,
                    "kl_n_terms": cfg.kl_n_terms,
                    "kl_landmarks": cfg.kl_landmarks,
                    "kl_corr_len_x": cfg.kl_corr_len_x,
                    "kl_corr_len_y": cfg.kl_corr_len_y,
                    "kl_kernel": cfg.kl_kernel,
                },
                "validation": {},
                "lifing": {},
                "rng": {
                    "base_seed": cfg.random_seed,
                    "seed_derivation_rule": "realization_seed = base_seed + realization_id",
                    "per_realization": [
                        {"realization_id": i, "seed": cfg.random_seed + i}
                        for i in range(cfg.n_realizations)
                    ],
                },
            },
        )

    runtime_cfg_path = cfg.run_dir / "runtime_config.json"
    runtime_cfg = load_runtime_config(runtime_cfg_path)
    geom_cfg = runtime_cfg.get("geometry", {})
    mat_cfg = runtime_cfg.get("material", {})
    if geom_cfg:
        cfg.geometry_type = geom_cfg.get("geometry_type", cfg.geometry_type)
        cfg.W = float(geom_cfg.get("W", cfg.W))
        cfg.H = float(geom_cfg.get("H", cfg.H))
        cfg.a = float(geom_cfg.get("a", cfg.a))
        cfg.crack_gap = float(geom_cfg.get("crack_gap", cfg.crack_gap))
        if "hole_radius" in geom_cfg:
            cfg.hole_radius = float(geom_cfg["hole_radius"])
        if "hole_center" in geom_cfg:
            hc = geom_cfg["hole_center"]
            cfg.hole_center = (float(hc[0]), float(hc[1]))
    if mat_cfg:
        cfg.nu = float(mat_cfg.get("nu", cfg.nu))
        cfg.plane_stress = bool(mat_cfg.get("plane_stress", cfg.plane_stress))
        cfg.thickness = float(mat_cfg.get("thickness", cfg.thickness))
        cfg.E_mean = float(mat_cfg.get("E_mean", mat_cfg.get("E", cfg.E_mean)))

    msh_path = cfg.run_dir / cfg.msh_name
    if not msh_path.exists():
        raise FileNotFoundError(f"Missing mesh file: {msh_path}. Run stochastic_mesh.py first.")

    pts, quad, _, _, _ = read_gmsh_quad_mesh(msh_path)
    centroids = element_centroids(pts, quad)

    kl_data = None
    if cfg.stochastic_E and cfg.E_mode == "kl_lognormal":
        basis_rng = np.random.default_rng(cfg.random_seed)
        kl_data = build_kl_basis(cfg, centroids, basis_rng)

    for i in range(cfg.n_realizations):
        solve_one(cfg, i, kl_data=kl_data, manifest_hash=manifest_hash)

    shared_geometry = geometry_payload(
        geometry_type=cfg.geometry_type,
        W=cfg.W,
        H=cfg.H,
        a=cfg.a,
        crack_gap=cfg.crack_gap,
        hole_radius=cfg.hole_radius if cfg.geometry_type == "plate_hole_edge_crack" else None,
        hole_center=cfg.hole_center if cfg.geometry_type == "plate_hole_edge_crack" else None,
    )
    update_runtime_config(
        runtime_cfg_path,
        stage="solver",
        updates={
            "run": {"name": cfg.run_name, "run_dir": cfg.run_dir},
            "geometry": shared_geometry,
            "material": material_payload(
                E=cfg.E_mean,
                E_mean=cfg.E_mean,
                nu=cfg.nu,
                plane_stress=cfg.plane_stress,
                thickness=cfg.thickness,
            ),
            "stage": {
                "mesh_path": msh_path,
                "n_realizations": cfg.n_realizations,
                "fields_pattern": "fields_mc*.npz" if cfg.n_realizations > 1 else "fields.npz",
                "resolved": {
                    "tip": shared_geometry["tip"],
                    "crack_start": shared_geometry["crack_start"],
                    "crack_dir": shared_geometry["crack_dir"],
                },
            },
        },
    )


if __name__ == "__main__":
    main()
