#!/usr/bin/env python3

"""
Extract a single K_I(a) value per crack length from DCM output CSVs.

Input files: the per-crack output generated by your DCM script:
    dcm_<something>_pairs_and_KI.csv

These have columns:
    r, cod, KI   (KI in Pa*sqrt(m), r in m)

We compute a robust estimate of plateau K_I by taking the median
over a user-defined fraction window in sorted r (default middle 50%).
"""

from __future__ import annotations
import argparse
from pathlib import Path
import pandas as pd
import numpy as np


def plateau_estimate(df: pd.DataFrame, frac_lo: float = 0.25, frac_hi: float = 0.75) -> float:
    """Median K_I over the [frac_lo, frac_hi] portion of sorted r."""
    if "r" not in df.columns or "KI" not in df.columns:
        raise ValueError("CSV must contain columns 'r' and 'KI'.")

    d = df.sort_values("r").reset_index(drop=True)
    n = len(d)
    if n < 5:
        raise ValueError(f"Not enough rows for a plateau estimate (n={n}). Need >= 5.")

    lo = int(frac_lo * n)
    hi = int(frac_hi * n)
    lo = max(0, min(lo, n - 1))
    hi = max(lo + 1, min(hi, n))

    KI_est = float(np.median(d["KI"].iloc[lo:hi]))
    return KI_est


def infer_a_mm_from_name(path: Path) -> float | None:
    """
    Tries to infer crack length 'a' in mm from filename patterns.
    Example: Crack_Length_8mm ... or ..._8mm...
    """
    name = path.stem.lower()
    for token in name.replace("-", "_").split("_"):
        if token.endswith("mm"):
            try:
                return float(token.replace("mm", ""))
            except ValueError:
                pass
    return None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--inputs", nargs="+", type=Path, required=True,
                    help="One or more DCM output CSVs (dcm_*_pairs_and_KI.csv).")
    ap.add_argument("--a-mm", nargs="*", type=float, default=None,
                    help="Optional explicit crack lengths in mm, same order as --inputs.")
    ap.add_argument("--frac-lo", type=float, default=0.25)
    ap.add_argument("--frac-hi", type=float, default=0.75)
    ap.add_argument("--out", type=Path, default=Path("KI_summary.csv"))
    args = ap.parse_args()

    if args.a_mm is not None and len(args.a_mm) not in (0, len(args.inputs)):
        raise SystemExit("--a-mm must be omitted or have the same count as --inputs")

    rows = []
    for i, f in enumerate(args.inputs):
        if not f.exists():
            raise SystemExit(f"Missing file: {f}")

        df = pd.read_csv(f)
        KI_est = plateau_estimate(df, args.frac_lo, args.frac_hi)  # Pa*sqrt(m)

        if args.a_mm and len(args.a_mm) == len(args.inputs):
            a_mm = float(args.a_mm[i])
        else:
            a_mm = infer_a_mm_from_name(f)
            if a_mm is None:
                raise SystemExit(
                    f"Could not infer crack length a (mm) from filename: {f.name}\n"
                    f"Provide --a-mm values explicitly."
                )

        rows.append({
            "file": str(f),
            "a_mm": a_mm,
            "KI_Pa_sqrt_m": KI_est,
            "KI_MPa_sqrt_m": KI_est / 1e6,
        })

    out = pd.DataFrame(rows).sort_values("a_mm").reset_index(drop=True)
    out.to_csv(args.out, index=False)
    print(f"Wrote: {args.out.resolve()}")
    print(out[["a_mm", "KI_MPa_sqrt_m"]])

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
